### ISSUE TITLE
MOZA Wheels

### ISSUE THREAD

**Issue by JacKeTUs** [JacKeTUs/linux-steering-wheels#2]
[MOZA_vid_pid_button_number.docx](https://github.com/JacKeTUs/linux-steering-wheels/files/15324190/MOZA_vid_pid_button_number.docx)
[Info.txt](https://github.com/JacKeTUs/linux-steering-wheels/files/15324191/Info.txt)

We have some files from MOZA with descriptor and VID/PID numbers.

Seems to me native PIDFF driver should do the trick, with duration fix.
https://github.com/JacKeTUs/moza-ff

**Comment by JacKeTUs** [comment]
After testing with WheelCheck.exe:
1. `SimpleSpring` effect does not work
2. `ConstantForce` does work
3. Dampers (Friction, Inertia) also working

Will wait for additional testing

**Comment by JacKeTUs** [comment]
Adding Moza wheels to the SDL whitelist
https://github.com/libsdl-org/SDL/pull/9803

**Comment by JacKeTUs** [comment]
One of the guys with the Moza R9 confirmed the wheel is working fine with ETS/ATS, but Damper/Friction effects are missing.
Wondering if it's due to PitHouse default settings (coefficient for Damper/Friction is 0)

**Comment by cjhelloletsgo** [comment]
Not sure if this is the right place to ask this but I am trying to get my Moza R5 working but it is not detected by steam, I think it should detected be since it is on the sdl whitelist now right? I also tried this suggestion in the README

Also, recent updates to SDL created SDL Hint variable to dynamically extend wheel devices list[17](https://github.com/JacKeTUs/linux-steering-wheels#user-content-fn-15-52e7281ea0014cd2f1ab0f06c7e837f6). You need to just export SDL_JOYSTICK_WHEEL_DEVICES=0x<VID>/0x<PID>,0x<VID2>/0x<PID2> before you launching something. 

so for this device: Bus 001 Device 014: ID 346e:0004 Gudsen MOZA R5 Base

I ran this command export SDL_JOYSTICK_WHEEL_DEVICES=0x346e/0x0004 
with no effect.

If I disable steam input then go into Dirt Rally 2.0 it detects Gudsen MOZA R5 Base but there is no forced feedback and all the inputs have to be manually mapped.

**Comment by JacKeTUs** [comment]
Hey, can you repeat that issue to https://github.com/JacKeTUs/moza-ff?

Before that, please, try `universal-quirks` branch from moza-ff driver, it should fix some envelope effects.

For manual mapping - sadly it's the norm for all games through Proton and for all bases. But when you set everything up and saved configs, when you launch the game second time *with the same controllers connected*, it should work right away

**Comment by cjhelloletsgo** [comment]
I unloaded the old module and retried with the universal-quirks branch but everything is the same from what I can tell. I can see the device with lsusb, no controller detected in steam, no forced feedback in Dirt Rally with Steam input disabled. I honestly don't know what envelope effects means so I could have missed something. If there is something specific that would be helpful I would be happy to try anything out.

Good to know on the manual mapping, this is my first time setting this up so I didn't know that having to do that was normal.

Since there didn't seem to be any change I will open an issue in the other repo like you mentioned.

**Comment by JacKeTUs** [comment]
Moza now should work with most FFB effects, and with Android app or BoxFlat, wheelbase config could be changed. I think i can close this issue

**Comment by esperanza-esperanza** [comment]
Do all the cavecats of using DirectDrive wheels on a game recognizing old-school wheels apply when using Wine?           
Can I play Need For Speed games on a Moza R3?              
People say it might not be possible without some setting up on Windows.       
And some older games on Windows straight up only work properly on the Logitech G29.         
I will be buying a Moza R3 this year.          

Edit:
Afaik Tokyo Xtreme Racer and a couple of my games play nicely with Direct Drive wheels.
